# Generated by Django 4.0.3 on 2022-06-16 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='nome',
            field=models.CharField(default='dog_default', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='servico',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='main.servico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autorizacao',
            name='autoriza',
            field=models.BooleanField(),
        ),
    ]
