# Generated by Django 4.0.3 on 2022-06-16 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_animal_nome_autorizacao_servico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=15)),
                ('osbervacao', models.TextField(max_length=200)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Autorizacao',
            new_name='Servico_Animal_Disponibilidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='descricao',
            new_name='servico',
        ),
        migrations.RenameField(
            model_name='servico_animal_disponibilidade',
            old_name='autoriza',
            new_name='disponivel',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='pessoa',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='main.pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='pessoa',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='main.pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pessoa'),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pessoa'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pessoa'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
