# Generated by Django 4.0.3 on 2022-06-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pessoa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartao',
            old_name='user',
            new_name='pessoa',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='user',
            new_name='pessoa',
        ),
    ]
