# Generated by Django 4.0.3 on 2022-06-16 19:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_animal_tutor_alter_carrinho_pessoa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='User_Dados',
        ),
    ]
