# Generated by Django 4.0.3 on 2022-06-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_tutor_animal_user_rename_pessoa_carrinho_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='cartao',
            options={'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='especie',
            options={'verbose_name': 'Espécie', 'verbose_name_plural': 'Espécies'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='raca',
            options={'verbose_name': 'Raça', 'verbose_name_plural': 'Raças'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='servico_animal_disponibilidade',
            options={'verbose_name': 'Disponibilidade de serviço', 'verbose_name_plural': 'Disponibilidades de serviço'},
        ),
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
        migrations.AlterModelOptions(
            name='user_dados',
            options={'verbose_name': 'Dados de usuário', 'verbose_name_plural': 'Dados dos usuários'},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='data',
            new_name='horario',
        ),
        migrations.RemoveField(
            model_name='user_dados',
            name='foto',
        ),
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(default='', upload_to='produtos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='foto',
            field=models.ImageField(default='', upload_to='servicos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('A', 'Ainda não iniciado'), ('B', 'Em andamento no pet shop'), ('C', 'Concluído, pet já em casa'), ('D', 'Concluído, aguardando retirada do pet')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(upload_to='pets'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='forma_entrada',
            field=models.CharField(choices=[('P', 'Buscar no endereço'), ('C', 'Cliente leva')], max_length=1),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='forma_saida',
            field=models.CharField(choices=[('P', 'Levar ao cliente'), ('C', 'Cliente busca')], max_length=1),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_entrega',
            field=models.CharField(choices=[('P', 'Delivery'), ('C', 'Retirada')], max_length=1),
        ),
    ]
