# Generated by Django 4.0.3 on 2022-06-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_animal_options_alter_carrinho_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='endereco',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.endereco'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('A', 'Ainda não iniciado'), ('B', 'Em andamento no pet shop'), ('C', 'Concluído, pet já em casa'), ('D', 'Concluído, aguardando retirada do pet')], default='A', max_length=1),
        ),
    ]
