# Generated by Django 4.0.3 on 2022-06-26 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_animal_especie_remove_raca_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.endereco'),
        ),
    ]
